spring:
  # 指定活动Profile
  profiles:
    active: postgre
---
spring:
  config:
    activate.on-profile: mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3306/springboot
    username: root
    password: 32147
---
spring:
  config:
    activate.on-profile: postgre
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/springboot
    username: postgres
    password: 32147
